id: I72F76C32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:10:14+00:00'
last_modified: '2022-06-09T04:51:03.051295+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4777
  title: སུམ་རྟགས་འགྲེལ་ཆེན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8895':
      image_group_id: I1PD338
      title: Volume 1 of sum rtags 'grel chen
      total_pages: 310
      order: 1
      base_file: 8895.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
