id: P007097
initial_creation_type: ocr
source_metadata:
  id: bdr:W4777
  title: སུམ་རྟགས་འགྲེལ་ཆེན
  author: ''
  volumes:
    b728d5c18cab4bef808a3e686809fb7b:
      image_group_id: I1PD338
      title: ''
      volume_number: 1
      total_pages: 310
ebook_metadata:
  title: སུམ་རྟགས་འགྲེལ་ཆེན
  author: ''
  sku: P007097
  cover: cover.jpg
  layers:
  - pagination
