id: P007097
initial_creation_type: ocr
source_metadata:
  id: bdr:W4777
  title: སུམ་རྟགས་འགྲེལ་ཆེན
  author: ''
  volumes:
    ba54e08afd9e44e1816323bb7084f496:
      image_group_id: I1PD338
      title: Volume 1 of sum rtags 'grel chen
      volume_number: 1
      total_pages: 310
      base_file: v001.txt
ebook_metadata:
  title: སུམ་རྟགས་འགྲེལ་ཆེན
  author: ''
  sku: P007097
  cover: cover.jpg
  layers:
  - pagination
